name: Maven Build

on:
  push:
    branches: [ main ] # Assuming you are using 'main' as your primary branch
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up OpenJDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt-openj9' # 使用 OpenJ9 分支的 OpenJDK 8

    - name: Build with Maven
      run: mvn clean install

    # Optional: You can also add steps to cache dependencies, deploy, etc.
