name: Build Elasticsearch Plugin with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package

    # If you wish to keep the built artifacts, you can use the upload-artifact action
    - name: Upload Plugin Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: elasticsearch-plugin-artifacts
        path: target/releases/*.zip # Assuming your plugin is zipped into the target/releases directory after build
